# Generated by Django 6.0.4 on 2026-05-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('rank', models.CharField(max_length=10)),
                ('cutoff', models.CharField(max_length=10)),
                ('products', models.TextField()),
            ],
        ),
    ]
