# Generated by Django 6.0.5 on 2026-05-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrequest',
            name='products',
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='cutoff',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='rank',
            field=models.CharField(max_length=20),
        ),
    ]
