# Generated by Django 6.0.5 on 2026-05-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0002_remove_productrequest_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='products',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
